#!/bin/bash

# init

cd /Users/reinfurt/Documents/Softwares/peano

ls

python peano.py 1 4 400 --screen_x 10 --screen_y 10 --midi &
python peano.py 2 4 400 --screen_x 10 --screen_y 410 --midi &
python peano.py 3 4 400 --screen_x 410 --screen_y 10 --midi &
python peano.py 4 4 400 --screen_x 410 --screen_y 410 --midi &
python peano.py 5 4 400 --screen_x 810 --screen_y 10 --midi &
python peano.py 6 4 400 --screen_x 810 --screen_y 410

exit
